package io.paperagent.v2.workspace;

/**
 * Stable machine-readable failures raised by the Workspace boundary.
 */
public enum WorkspaceErrorCode {
    REQUIRED_VALUE_MISSING,
    INVALID_LIMIT,
    INVALID_METADATA,
    SOURCE_FAILURE,
    SOURCE_REFERENCE_MISMATCH,
    DUPLICATE_PATH,
    PATH_COLLISION,
    HASH_MISMATCH,
    FILE_LIMIT_EXCEEDED,
    AGGREGATE_LIMIT_EXCEEDED,
    FILE_COUNT_LIMIT_EXCEEDED,
    WORKSPACE_ALREADY_EXISTS,
    WORKSPACE_NOT_FOUND,
    WORKSPACE_SPEC_CONFLICT,
    WORKSPACE_RETIRED,
    WORKSPACE_PARTIAL_STATE,
    WORKSPACE_REFERENCE_MISMATCH,
    PATH_NOT_FOUND,
    PATH_ALREADY_EXISTS,
    PATH_ESCAPE,
    LINK_ESCAPE,
    NOT_REGULAR_FILE,
    TEMPORARY_PATH_OCCUPIED,
    SOURCE_MANIFEST_FINGERPRINT_MISMATCH,
    MATERIALIZATION_VERIFICATION_FAILED,
    ATOMIC_PUBLISH_NOT_SUPPORTED,
    IO_FAILURE
}
