ALTER TABLE sys_users ADD COLUMN role VARCHAR(32) NOT NULL DEFAULT 'USER';
ALTER TABLE sys_users ADD COLUMN login_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sys_users ADD COLUMN ai_quota_total BIGINT NOT NULL DEFAULT -1;
ALTER TABLE sys_users ADD COLUMN ai_quota_used BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sys_users ADD COLUMN last_login_at TIMESTAMP NULL;

UPDATE invite_codes SET max_uses = 5 WHERE max_uses > 5;

CREATE TABLE ai_usage_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    feature VARCHAR(32) NOT NULL,
    prompt_tokens BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_tokens BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_usage_records_user FOREIGN KEY (user_id) REFERENCES sys_users(id)
);

CREATE INDEX idx_ai_usage_records_user_created ON ai_usage_records(user_id, created_at);
