CREATE TABLE agent_v2_turn_intakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    client_request_id VARCHAR(128) NOT NULL,
    request_sha256 VARCHAR(64) NOT NULL,
    content_text CLOB NOT NULL,
    rag_disabled BOOLEAN NOT NULL,
    skill_id VARCHAR(128),
    experiment_json CLOB,
    user_message_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL UNIQUE,
    assistant_message_id BIGINT,
    plan_id VARCHAR(128) UNIQUE,
    planner_output_json CLOB,
    capability_bindings_json CLOB,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(64),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_v2_turn_intake_request
        UNIQUE (user_id, session_id, client_request_id),
    CONSTRAINT ck_agent_v2_turn_intake_status CHECK
        (status IN ('RUNNING', 'DIRECT', 'PERSISTENT', 'FAILED'))
);
