CREATE TABLE agent_v2_adaptive_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    client_request_id VARCHAR(128) NOT NULL,
    route VARCHAR(32) NOT NULL,
    plan_id VARCHAR(128),
    project_version VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    steps_json CLOB NOT NULL,
    final_text CLOB,
    candidate_artifact_id VARCHAR(128),
    output_paths_json CLOB NOT NULL,
    error_code VARCHAR(64),
    reflection_count INT NOT NULL,
    replan_count INT NOT NULL,
    repair_count INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_v2_adaptive_request
        UNIQUE (user_id, session_id, client_request_id),
    CONSTRAINT ck_agent_v2_adaptive_status CHECK
        (status IN ('PLANNING','RUNNING','WAITING_CONFIRMATION','SUCCEEDED','FAILED'))
);
