CREATE TABLE agent_v2_adaptive_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intake_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    client_request_id VARCHAR(128) NOT NULL,
    route VARCHAR(32) NOT NULL,
    plan_id VARCHAR(128),
    project_version VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    steps_json CLOB NOT NULL,
    final_text CLOB,
    candidate_artifact_id BIGINT,
    output_paths_json CLOB NOT NULL,
    error_code VARCHAR(64),
    reflection_count INT NOT NULL,
    replan_count INT NOT NULL,
    repair_count INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_v2_adaptive_request
        UNIQUE (user_id, session_id, client_request_id),
    CONSTRAINT ck_agent_v2_adaptive_status CHECK
        (status IN ('PLANNING','RUNNING','WAITING_CONFIRMATION','SUCCEEDED','FAILED'))
);

CREATE TABLE agent_v2_natural_candidate_authorities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    plan_id VARCHAR(128) NOT NULL UNIQUE,
    step_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL,
    project_version VARCHAR(255) NOT NULL,
    objective VARCHAR(2000) NOT NULL,
    paths_json CLOB NOT NULL,
    authority_json CLOB NOT NULL,
    authority_sha256 VARCHAR(64) NOT NULL,
    replacements_json CLOB,
    diff_fingerprint VARCHAR(64),
    candidate_artifact_id BIGINT,
    candidate_fingerprint VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_v2_natural_candidate_step
        UNIQUE (plan_id, step_id),
    CONSTRAINT ck_agent_v2_natural_candidate_status CHECK
        (status IN ('BOUND','PREPARED','PUBLISHED'))
);
