package io.paperagent.v2.runtime.execution.recovery.composition;

public enum ExecutionStartRecoveryProtocolCode {
    NULL_COLLABORATOR_RESULT,
    UNEXPECTED_PERSISTENCE_OUTCOME,
    COLLABORATOR_EXCEPTION,
    INCONSISTENT_INSPECTION_RESULT,
    INCONSISTENT_MATERIALIZATION_AUTHORITY,
    INCONSISTENT_LEASE_AUTHORITY,
    INCONSISTENT_EXECUTION_START_RESULT
}
