package io.paperagent.v2.sandbox;

/**
 * Stable machine-readable validation codes for Sandbox protocol values.
 */
public enum SandboxValidationCode {
    REQUIRED_VALUE_MISSING,
    REQUIRED_TEXT_BLANK,
    REQUIRED_COLLECTION_EMPTY,
    NULL_COLLECTION_ELEMENT,
    INVALID_ID,
    INVALID_TEXT_CHARACTER,
    BOUND_EXCEEDED,
    INVALID_ENVIRONMENT_NAME,
    ENVIRONMENT_NAME_COLLISION,
    CAPABILITY_NOT_GRANTED,
    SECRET_REFERENCE_NOT_AUTHORIZED,
    INVALID_TIME_RANGE,
    INVALID_OUTPUT_BYTE_COUNT,
    OUTPUT_LENGTH_OVERFLOW,
    OUTPUT_LIMIT_EXCEEDED,
    INVALID_SCRIPT
}
