CREATE TABLE agent_engine_product_turns (
    id BIGINT NOT NULL AUTO_INCREMENT,
    engine_mode VARCHAR(16) NOT NULL,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    project_version CHAR(64) NOT NULL,
    root_client_request_id VARCHAR(128) NOT NULL,
    engine_task_id VARCHAR(69) NOT NULL,
    request_digest CHAR(64) NOT NULL,
    product_request_digest CHAR(64) NOT NULL,
    authority_json LONGTEXT NOT NULL,
    question LONGTEXT NOT NULL,
    user_message_id BIGINT NOT NULL,
    agent_turn_id BIGINT NOT NULL,
    assistant_message_id BIGINT NULL,
    engine_state VARCHAR(32) NOT NULL,
    last_sequence BIGINT NOT NULL DEFAULT 0,
    pending_question_id VARCHAR(128) NULL,
    pending_question_text TEXT NULL,
    final_text LONGTEXT NULL,
    receipt_refs_json LONGTEXT NULL,
    failure_category VARCHAR(32) NULL,
    failure_code VARCHAR(96) NULL,
    last_answer_client_request_id VARCHAR(128) NULL,
    last_answer_digest CHAR(64) NULL,
    last_answer_question_id VARCHAR(128) NULL,
    last_cancel_client_request_id VARCHAR(128) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_engine_product_turn_request (user_id, session_id, root_client_request_id),
    UNIQUE KEY uk_engine_product_turn_task (engine_task_id),
    CONSTRAINT ck_engine_product_turn_mode CHECK (engine_mode IN ('DSH','CODEX')),
    CONSTRAINT ck_engine_product_turn_state CHECK (
        engine_state IN ('queued','running','waiting_user','succeeded','failed','cancelled'))
);
