package com.yanban.api.agent.v2.bootstrap;

public enum AuthenticatedAgentTurnStepActivationCompositionCode {
    REQUIRED_VALUE_MISSING,
    INSPECTION_COLLABORATOR_FAILURE,
    INVALID_INSPECTION_RESULT,
    EXECUTION_START_NOT_FOUND,
    EXECUTION_START_NOT_COMMITTED,
    EXECUTION_START_REJECTED,
    EXECUTION_START_PLAN_MISMATCH,
    MALFORMED_COMMITTED_START
}
