package com.yanban.api.agent.v2.loop;

public enum PersistentPlanAgentLoopState {
    PLAN_SUCCEEDED,
    REPLAN_REQUIRED,
    REPLAN_APPLIED,
    REPLAN_REPLAYED,
    REPLAN_REJECTED,
    RECOVERY_REJECTED,
    ACTIVATION_REJECTED,
    KERNEL_PERSISTENCE_REJECTED,
    UNSUPPORTED_INTENT,
    EFFECT_REJECTED,
    PROGRESSION_REJECTED
}
