package io.paperagent.v2.runtime.execution.context.composition;

public enum PlanExecutionContextCompositionStage {
    INITIAL_EXECUTION_START_INSPECT,
    INITIAL_CONTEXT_INSPECT,
    LEASE_ACQUIRE,
    POST_LEASE_EXECUTION_START_INSPECT,
    POST_LEASE_CONTEXT_INSPECT,
    RESERVE,
    POST_RESERVE_CONTEXT_INSPECT,
    WORKSPACE_INSPECT,
    WORKSPACE_MATERIALIZE,
    POST_MATERIALIZE_WORKSPACE_INSPECT,
    CONFIRM,
    POST_CONFIRM_CONTEXT_INSPECT
}
