package io.paperagent.v2.runtime.execution.context.composition;

public enum PlanExecutionContextCompositionProtocolCode {
    NULL_COLLABORATOR_RESULT,
    UNEXPECTED_PERSISTENCE_OUTCOME,
    COLLABORATOR_EXCEPTION,
    INCONSISTENT_EXECUTION_START_AUTHORITY,
    INCONSISTENT_LEASE_AUTHORITY,
    INCONSISTENT_CONTEXT_AUTHORITY,
    INCONSISTENT_WORKSPACE_AUTHORITY,
    INCONSISTENT_RECONCILIATION_AUTHORITY
}
