package io.paperagent.v2.contracts;

/**
 * Stable machine-readable contract validation codes.
 */
public enum ViolationCode {
    REQUIRED_VALUE_MISSING,
    REQUIRED_TEXT_BLANK,
    INVALID_ID,
    NULL_COLLECTION_ELEMENT,
    DUPLICATE_ID,
    INVALID_TIME_RANGE,
    INVALID_WORKSPACE_LIMIT,
    INVALID_ROUTE,
    INVALID_PATH,
    INVALID_HASH,
    INVALID_DIFF_ENTRY,
    INVALID_RECEIPT,
    OUTPUT_LIMIT_EXCEEDED,
    SECRET_VALUE_NOT_ALLOWED,
    CAPABILITY_NOT_GRANTED,
    UNKNOWN_STEP_DEPENDENCY,
    SELF_DEPENDENCY,
    STEP_DEPENDENCY_CYCLE,
    REVISION_NOT_MONOTONIC,
    REVISION_PARENT_MISMATCH,
    TASK_FRAME_MISMATCH,
    COMPLETED_FACT_REMOVED,
    COMPLETED_FACT_REDEFINED,
    CHECKPOINT_PLAN_MISMATCH,
    CHECKPOINT_REVISION_MISMATCH,
    CHECKPOINT_REVISION_REGRESSION,
    CHECKPOINT_UNKNOWN_STEP,
    CHECKPOINT_COMPLETION_FACT_MISSING,
    CHECKPOINT_RECEIPT_REGRESSION,
    CHECKPOINT_STATE_INCONSISTENT,
    CHECKPOINT_STATE_REGRESSION,
    CHECKPOINT_TIME_REGRESSION,
    EVENT_SEQUENCE_REGRESSION,
    INCONSISTENT_REFERENCE
}
