package io.paperagent.v2.runtime.execution.kernel;

public enum SingleTurnStepKernelProtocolCode {
    NULL_COLLABORATOR_RESULT,
    UNKNOWN_TURN_DECISION,
    COLLABORATOR_EXCEPTION,
    INCONSISTENT_RECOVERED_AUTHORITY,
    INCONSISTENT_DECISION_AUTHORITY,
    UNEXPECTED_PERSISTENCE_OUTCOME,
    INCONSISTENT_PERSISTED_INTENT
}
