package io.paperagent.v2.chain.context;

public enum ChainContextErrorCode {
    CONTEXT_REVISION_NOT_BUILDING,
    CONTEXT_PARENT_REVISION_NOT_FOUND,
    CONTEXT_PARENT_REVISION_INVALID,
    CONTEXT_SOURCE_MODULE_SET_INVALID,
    CONTEXT_SOURCE_MODULE_DUPLICATE,
    CONTEXT_SOURCE_MODULE_MISSING,
    CONTEXT_MODULE_DIGEST_MISMATCH,
    CONTEXT_MODULE_REQUIREMENTS_MISSING,
    CONTEXT_EMPTY_PROJECTION_INVALID,
    CONTEXT_REQUIRED_MODULE_EMPTY,
    CONTEXT_INPUT_BLOCKED,
    CONTEXT_REVISION_NOT_FOUND,
    CONTEXT_REVISION_TASK_MISMATCH,
    CONTEXT_REVISION_NOT_RECOVERABLE,
    CONTEXT_REVISION_MANIFEST_MISMATCH,
    CONTEXT_MODULE_REPLAY_MISMATCH,
    CONTEXT_BODY_PAGE_INVALID
}
