package com.yanban.api.agent;

/** Display-safe audit codes produced only from server-observed runtime facts. */
public enum DomainVerificationReasonCode {
    MATERIAL_COVERAGE_VERIFIED,
    MATERIAL_TOOL_UNAVAILABLE,
    REQUIRED_TOOL_EXECUTED_SUCCESSFULLY,
    REQUIRED_TOOL_NOT_EXECUTED,
    REQUIRED_TOOL_FAILED,
    CURRENT_TRUSTED_EVIDENCE_PRESENT,
    CURRENT_TRUSTED_EVIDENCE_MISSING_OR_INVALID,
    PLAN_STEP_FAILED,
    PLAN_STEP_PARTIAL,
    PLAN_STEP_SKIPPED,
    RUNTIME_BUDGET_EXHAUSTED,
    CONSISTENCY_VERIFIED_CONSISTENT_BY_STRUCTURED_FACT,
    CONSISTENCY_VERIFIED_INCONSISTENT_BY_STRUCTURED_FACT,
    CONSISTENCY_FACT_CONFLICT,
    CONSISTENCY_UNRESOLVED,
    REFLECTION_ELIGIBLE,
    REFLECTION_NOT_ELIGIBLE
}
