package io.paperagent.v2.chain;

public enum ChainTransitionStage {
    OPEN,
    NORMAL_SUCCESSOR_COMMITTED,
    PENDING_RESOLVED,
    ACCEPTED_RESULT_COMMITTED,
    APPLICABILITY_COMMITTED,
    STEP_COMPLETED,
    NEXT_STEP_ACTIVATED_OR_NONE,
    TASKFRAME_PLAN_COMMITTED,
    OLD_STEP_SUPERSEDED_OR_NONE,
    NEW_STEP_ACTIVATED,
    ACCEPTED_RESULT_COMMITTED_OR_VERIFIED,
    APPLICABILITY_COMMITTED_OR_EMPTY,
    STEP_COMPLETED_OR_VERIFIED,
    READINESS_COMMITTED,
    READINESS_VERIFIED,
    FINALIZATION_CHECK_COMMITTED,
    PUBLISH_COMMITTED_OR_NOT_REQUIRED,
    TASK_OUTCOME_COMMITTED,
    FAILED_CHECK_HANDOFF_COMMITTED,
    COMPLETE
}
